# NumPy

NumPy - Numerical Python
Biblioteca para cálculos matemáticos
Fornece a base matemática necessária para análise de dados, Aprendizado de Máquina, Estatística, entre outros.
Facilita:
- A criação de Array e Matrizes
- A leitura de datasets
- Álgebra linear

In [1]:
import numpy as np

Também é possível importar desta forma:

from numpy import *

Lista de Dados Python:
- Conjunto de valores de qualquer tipo:
Ex: lista = [1, 20, 'Texto', True, 2.3]

Array NumPy:
- Conjunto de valores de apenas 1 tipo;
- São mais eficientes do que lista no que diz respeito o uso de memória do computador;

In [2]:
array_1 = np.array([1, 2, 3, 4, 5])

In [3]:
print(type(array_1))

<class 'numpy.ndarray'>


In [4]:
print(array_1)

[1 2 3 4 5]


In [5]:
print(array_1[1])

2


In [6]:
print(array_1.size)

5


# Propriedades/Atributos do NumPy

In [7]:
#shape retorna a dimensão/formato do array
print(array_1.shape)

(5,)


In [8]:
#Retorna o tipo dos dados armazenados
print(array_1.dtype)

int32


In [9]:
#Retorna o tamanho de cada elemento (quanto ocupa na memória)
print(array_1.itemsize)

4


In [10]:
#Retorna o tamanho de todos os elementos do array (4x5 = 20)
print(array_1.nbytes)

20


#  Tipos de Arrays

In [11]:
#Array de Inteiros
array_inteiros = np.array([1, 2, 3, 4, 5])
print(array_inteiros)

[1 2 3 4 5]


In [12]:
#Array de Números Reais
array_reais = np.array([2.5, 1.0, 5.2, 10.2])
print(array_reais)

[ 2.5  1.   5.2 10.2]


In [13]:
#Array de Strings
array_strings = np.array(['Python', 'Javascript', 'Java'])
print(array_strings)

['Python' 'Javascript' 'Java']


In [14]:
#Array de valores Booleanos
array_booleanos = np.array([True, True, False])
print(array_booleanos)

[ True  True False]


In [17]:
array_reais_forcado = np.array([5, 2, 1, 67, 1], dtype=np.float32)
print(array_reais_forcado.dtype)
print(array_reais_forcado)

float32
[ 5.  2.  1. 67.  1.]


# Matriz

In [3]:
matriz_1 = np.array([[1, 2], [3, 4], [4, 5], [5, 6]])
print(matriz_1)

[[1 2]
 [3 4]
 [4 5]
 [5 6]]


In [5]:
#A dimensão desta matriz é 4 (linhas) por 2 (colunas)
print(matriz_1.shape)

(4, 2)


In [10]:
#Para imprimir, basta informar a "linha" e "coluna" entre colchetes
print(matriz_1[2][1])
#Outra forma de Imprimir
print(matriz_1[2,0])

5
4


In [13]:
#Para substituir também utiliza colchetes
matriz_1[2][1] = 10
print(matriz_1[2][1])

#Outra forma
matriz_1[2,0] = 15
print(matriz_1[2,0])

#Matriz completa com os dados substituídos
print(matriz_1)

10
15
[[ 1  2]
 [ 3  4]
 [15 10]
 [ 5  6]]


# Funções para Array

In [14]:
#cumsum - retorna uma matriz com a soma acumulada dos valores
array_2 = np.array([2, 3, 1, 5, 10])
print(array_2.cumsum())

[ 2  5  6 11 21]


In [16]:
#arange - Cria uma matriz seguindo a lógica do range nativo do python
array_3 = np.arange(5)
print(array_3)

array_4 = np.arange(2, 10, 2)
print(array_4)

[0 1 2 3 4]
[2 4 6 8]


In [19]:
#linspace
#Cria um array com elementos espaçados igualmente 
#entre um valor inicial e final
# linspace(inicio, fim, quantidade de elementos entre eles)
array_5 = np.linspace(1, 10, 4)
print(array_5)

[ 1.  4.  7. 10.]


In [20]:
#zeros - Cria um array somente com elementos 0
array_6 = np.zeros(15)
print(array_6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
#array_equal
#Compara se 2 arrays são iguais (true ou false)
array_7 = np.array([1,2,3,4])
array_8 = np.array([5,6,7,8])
print(np.array_equal(array_7, array_8))

False


In [16]:
array_9 = np.array([1,2,3,4])
array_10 = np.array([1,2,3,4])
print(np.array_equal(array_9, array_10))

True


In [17]:
#min
#Retorna o menor valor (mínimo)
print(array_10.min())

1


In [18]:
#max
#Retorna o maior valor (máximo)
print(array_10.max())

4


In [22]:
#repeat
#Cria um novo array com os elementos repetidos
#Repete por número
print(array_10)
print(np.repeat(array_10, 3))

[1 2 3 4]
[1 1 1 2 2 2 3 3 3 4 4 4]


In [23]:
#tile
#Repete os elementos de um array
#repete os elementos na ordem original do array
print(array_10)
print(np.tile(array_10,3))

[1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


In [30]:
#concatenate
#junta 2 arrays e gera um com todos os elementos
print(np.concatenate((array_7, array_8), axis=0))

[1 2 3 4 5 6 7 8]


# Funções para Matriz

In [2]:
#eye - Cria uma matriz quadrada, todos os elementos são zero com 
#exceção dos elementos que foram a diagonal principal, estes 
# recebem o valor 1
matriz_2 = np.eye(3)
print(matriz_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
#diag
#define os elementos que ficarão na diagonal principal da matriz
matriz_3 = np.diag(np.array([2,4,1,0]))
print(matriz_3)

[[2 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 0]]


In [6]:
#ones
#Cria uma matriz com todos os valores sendo 1
matriz_4 = np.ones((3,4))
print(matriz_4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#matrix
#converte lista bidimensional em matriz numpy
lista_bidimensional = [[1,2,3],[4,5,6],[7,8,9]]
matriz_5 = np.matrix(lista_bidimensional)
print(matriz_5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#flatten
#Transforma a matriz principal em uma nova em que todos os 
#elementos ficarão na primeira linha.
array_7 = matriz_5.flatten()
print(array_7)

[[1 2 3 4 5 6 7 8 9]]


# Propriedades para Matriz

In [8]:
#shape
#imprime quantas linhas e colunas a matriz possui
print(matriz_5.shape)

(3, 3)


In [9]:
#ndim
#Retorna a dimensão da matriz
#No exemplo a seguir, possui 2 dimensões (linha x coluna)
print(matriz_5.ndim)

2


In [10]:
#size
#Retorna quantos elementos possui a matriz
print(matriz_5.size)

9


# Slicing em Arrays

In [2]:
array_11 = np.array([10, 4, 2, 1, 11, 44])
print(array_11)

[10  4  2  1 11 44]


In [3]:
#Imprime o terceiro elemento do array
print(array_11[2])

2


In [4]:
#Utilizando slicing é possível retornar uma parte do array
#No exemplo a seguir, retorna os elementos da posição 1 até a 3
print(array_11[1:3])

[4 2]


In [5]:
#O exemplo a seguir retornará os elementos nas posições 1, 3 e 5
print(array_11[::2])

[10  2 11]


In [6]:
#Retornará os elementos das posições 0 e 3 (salto será 3)
print(array_11[0:4:3])

[10  1]


# Trabalhando com Dataset

In [13]:
arquivo = np.loadtxt('country_wise_latest.csv', delimiter=',', usecols=(1,2,3), skiprows=1, dtype=np.int32)

In [14]:
print(arquivo)

[[  36263    1269   25198]
 [   4880     144    2745]
 [  27973    1163   18837]
 [    907      52     803]
 [    950      41     242]
 [     86       3      65]
 [ 167416    3059   72575]
 [  37390     711   26665]
 [  15303     167    9311]
 [  20558     713   18246]
 [  30446     423   23242]
 [    382      11      91]
 [  39482     141   36110]
 [ 226225    2965  125683]
 [    110       7      94]
 [  67251     538   60492]
 [  66428    9822   17452]
 [     48       2      26]
 [   1770      35    1036]
 [     99       0      86]
 [  71181    2647   21478]
 [  10498     294    4930]
 [    739       2      63]
 [2442375   87618 1846641]
 [    141       3     138]
 [  10621     347    5585]
 [   1100      53     926]
 [    350       6     292]
 [    378       1     301]
 [   2328      22    1550]
 [    226       0     147]
 [  17110     391   14539]
 [ 116458    8944       0]
 [   4599      59    1546]
 [    922      75     810]
 [ 347923    9187  319954]
 [  86783    4656   78869]
 

# Conceitos Básicos de Estatística

In [15]:
array_12 = np.array([15,23,72,22])

In [16]:
#sum
#retorna o resultado da soma de todos os elementos
print(np.sum(array_12))

132


In [17]:
#prod
#retorna o resultado do produto(multiplicação) de todos os elementos
print(np.prod(array_12))

546480


In [18]:
#cumsum
#retorna um array com o resultado da soma acumulada de todos os elementos
print(np.cumsum(array_12))

[ 15  38 110 132]


In [19]:
#mean
#Média aritmética entre os elementos do array
print(np.mean(array_12))

33.0


In [30]:
#mediana
#retorna o valor central do array
print(np.median(array_12))

22.5


In [31]:
#Desvio Padrão
#Variação dos dados do array em relação à média
#Também chamado de dispersão
print(np.std(array_12))

22.726636354727024


In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
print(np.sum(matriz, axis=0))