# NumPy

NumPy - Numerical Python
Biblioteca para cálculos matemáticos
Fornece a base matemática necessária para análise de dados, Aprendizado de Máquina, Estatística, entre outros.
Facilita:
- A criação de Array e Matrizes
- A leitura de datasets
- Álgebra linear

In [1]:
import numpy as np

Também é possível importar desta forma:

from numpy import *

Lista de Dados Python:
- Conjunto de valores de qualquer tipo:
Ex: lista = [1, 20, 'Texto', True, 2.3]

Array NumPy:
- Conjunto de valores de apenas 1 tipo;
- São mais eficientes do que lista no que diz respeito o uso de memória do computador;

In [2]:
array_1 = np.array([1, 2, 3, 4, 5])

In [3]:
print(type(array_1))

<class 'numpy.ndarray'>


In [4]:
print(array_1)

[1 2 3 4 5]


In [5]:
print(array_1[1])

2


In [6]:
print(array_1.size)

5


# Propriedades/Atributos do NumPy

In [7]:
#shape retorna a dimensão/formato do array
print(array_1.shape)

(5,)


In [8]:
#Retorna o tipo dos dados armazenados
print(array_1.dtype)

int32


In [9]:
#Retorna o tamanho de cada elemento (quanto ocupa na memória)
print(array_1.itemsize)

4


In [10]:
#Retorna o tamanho de todos os elementos do array (4x5 = 20)
print(array_1.nbytes)

20


#  Tipos de Arrays

In [11]:
#Array de Inteiros
array_inteiros = np.array([1, 2, 3, 4, 5])
print(array_inteiros)

[1 2 3 4 5]


In [12]:
#Array de Números Reais
array_reais = np.array([2.5, 1.0, 5.2, 10.2])
print(array_reais)

[ 2.5  1.   5.2 10.2]


In [13]:
#Array de Strings
array_strings = np.array(['Python', 'Javascript', 'Java'])
print(array_strings)

['Python' 'Javascript' 'Java']


In [14]:
#Array de valores Booleanos
array_booleanos = np.array([True, True, False])
print(array_booleanos)

[ True  True False]


In [17]:
array_reais_forcado = np.array([5, 2, 1, 67, 1], dtype=np.float32)
print(array_reais_forcado.dtype)
print(array_reais_forcado)

float32
[ 5.  2.  1. 67.  1.]
