# Numpy

Numpy = Numerical Python
Pacote para operações matemáticas que suportam estatística, análise 
de dados, inteligênica artificial, entre outras.

- Numpy trabalha com o conceito de Array e tem suporte a leitura de datasets;
- Disponibiliza diversas funções de cálculos matemáticos e estatísticos;

Site Oficial: https://numpy.org

Instalação: pip install numpy

## Array Numpy

Array numpy é uma lista de dados de mesmo tipo

Nomenclatura oficial: ndarray

- 1-D array - array com 1 dimensão - vetor, lista
- 2-D array - array com 2 dimensões - matriz
- 3-D ou mais array - array com 3 ou mais dimensões - tensor

In [1]:
# Importando a biblioteca
import numpy as np

In [2]:
# Criando um array numpy - função array()
array_01 = np.array([2,6,5,1,55])
print(array_01)

[ 2  6  5  1 55]


In [3]:
# type() - é uma função python para visualizar o tipo de dado
array_01 = np.array([2,6,5,1,55])
print(type(array_01))

<class 'numpy.ndarray'>


## Propriedades

In [4]:
# dtype - Imprime o tipo dos dados do array numpy
array_01 = np.array([2,6,5,1,55])
print(array_01.dtype)

int32


In [5]:
# shape - dimensão e qtd de elementos do array numpy
array_01 = np.array([2,6,5,1,55])
print(array_01.shape)

(5,)


In [17]:
# size - quantidade de elementos do array
array_01 = np.array([2,6,5,1,55])
print(array_01.size)

5


## Funções

In [18]:
# cumsum() - gera um novo array numpy com a soma acumulada dos elementos
array_01 = np.array([2,6,5,1,55])
print(array_01.cumsum())

[ 2  8 13 14 69]


In [20]:
# arange() - cria um array numpy seguindo a mesma lógica da função range()
array_01 = np.arange(10)
print(array_01)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
array_01 = np.arange(2,10)
print(array_01)

[2 3 4 5 6 7 8 9]


In [23]:
array_01 = np.arange(2,10,4)
print(array_01)

[2 6]


In [27]:
'''
linspace() - gera um array numpy que:
(1,10,4)
1 - Número inicial do intervalo
10 - Número final do intervalo
4 - Deve preencher o array com 4 elementos deste intervalo com 
o mesmo espaçamento entre eles

'''
array_01 = np.linspace(1,10,4)
print(array_01)

[ 1.  4.  7. 10.]


In [28]:
# equal() - compara elementos de arrays numpy, resultando em um array de booleanos
array_02 = np.array([1,4,7,4])
array_03 = np.array([2,4,7,4])
print(np.equal(array_02, array_03))

[False  True  True  True]


In [29]:
# array_equal() - compara se o array é igual a outro
array_02 = np.array([1,4,7,4])
array_03 = np.array([2,4,7,4])
print(np.array_equal(array_02, array_03))

False


## Slicing de Arrays numpy (fatiamento)

In [32]:
array_04 = np.arange(20)
print(array_04)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [33]:
print(array_04[5:15:2])

[ 5  7  9 11 13]


In [35]:
print(array_04[5::])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
