# Slicing de Arrays de 2 dimensões

In [ ]:
# Slicing significa fatiar; utiliza colchetes []

In [1]:
import numpy as np

In [2]:
# Revisão: slicing de array de 1 dimensão
array_1 = np.array([1,2,3,4,5])
print(array_1[2:5])

[3 4 5]


In [3]:
print(array_1[2:])

[3 4 5]


In [4]:
print(array_1[:2])

[1 2]


In [7]:
array_1 = np.array([0,1,2,3,4,5])
print(array_1[0:6:2])

[0 2 4]


In [10]:
array_1 = np.array([0,1,2,3,4,5])
print(array_1[::2])

[0 2 4]


In [11]:
array_1 = np.array([0,1,2,3,4,5])
print(array_1[-5:5])

[1 2 3 4]


In [19]:
array_1 = np.array([0,1,2,3,4,5])
print(array_1[::-1])

[5 4 3 2 1 0]


## Slicing em Array de duas dimensões

In [27]:
array_2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array_2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
print(array_2[2:4,1:3])

[[ 8  9]
 [11 12]]


In [29]:
print(array_2[1:,:2])

[[ 4  5]
 [ 7  8]
 [10 11]]


In [30]:
print(array_2[3:4,0:1])

[[10]]


In [31]:
print(array_2[3:,:1])

[[10]]


In [42]:
print(array_2[0:1,0:1])
print(array_2[1:2,1:2])
print(array_2[2:3,2:3])

[[1]]
[[5]]
[[9]]


In [45]:
print(np.diag(array_2, k=-1))

[ 4  8 12]
