# 2darray - Array de 2 dimensões

In [2]:
import numpy as np

## Criação de um 2darray

In [3]:
# Utiliza também a função array()
array_1 = np.array([[1,2,3],[4,5,6]])

In [4]:
print(array_1)

[[1 2 3]
 [4 5 6]]


In [9]:
print(type(array_1))

<class 'numpy.ndarray'>


### Acessando elementos do Array de 2 dimensões

In [10]:
# Sempre na sequência: linha x coluna. Se usa colchetes []
# linha 1; coluna 1
print(array_1[1][1])

5


In [11]:
#linha 0; coluna 2
print(array_1[0][2])

3


In [12]:
#linha 0; coluna 1
print(array_1[0,1])

2


In [13]:
# Para substituir um valor se utiliza colchetes também
array_1[0][1] = 30
print(array_1)

[[ 1 30  3]
 [ 4  5  6]]


In [14]:
array_1[1,0] = 15
print(array_1)

[[ 1 30  3]
 [15  5  6]]


## Propriedades para 2darray

In [15]:
# shape - retorna a quantidade de elementos por dimensão
print(array_1.shape)

(2, 3)


In [17]:
# size - quantidade total de elementos no array
print(array_1.size)

6


In [18]:
# ndim - retorna a dimensão do array
print(array_1.ndim)

2


## Funções para 2darray

In [19]:
# cumsum() - soma acumulada
print(array_1.cumsum())

[ 1 31 34 49 54 60]


In [21]:
# reshape - modifica a dimensão do array
array_d1 = np.array([1,2,3,4,5,6])
array_2 = array_d1.reshape(2,3)
print(array_2)

[[1 2 3]
 [4 5 6]]


In [22]:
'''
A função cumsum() gera um array de 1 dimensão. No exemplo a seguir, foi acumulado
com a função reshape(), que é executada em seguida gerando novamente o array
de duas dimensões.
'''
print(array_1.cumsum().reshape(2,3))

[[ 1 31 34]
 [49 54 60]]


In [26]:
array_3 = np.array(range(1,11)).reshape(5,2)
print(array_3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
